 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Parapente                                                   
     # Surfaces =   2
     # Strips   =  40
     # Vortices = 280

  Sref =  5.1000       Cref =  1.0000       Bref =  5.1000    
  Xref = 0.61740       Yref =  0.0000       Zref = -2.6975    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   6.39146     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.03784     Cltot =  -0.00000     Cl'tot =  -0.00000
  CYtot =   0.00000     Cmtot =   0.00000
  CZtot =  -0.41453     Cntot =   0.00000     Cn'tot =   0.00000

  CLtot =   0.41617
  CDtot =   0.00854
  CDvis =   0.00000     CDind = 0.0085450
  CLff  =   0.42430     CDff  = 0.0094028    | Trefftz
  CYff  =  -0.00000         e =    1.1950    | Plane  

   Simetrico       =   0.00000
   Asimetrico      =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   3.634085    CLb =  -0.000000
 y  force CY |    CYa =   0.000000    CYb =  -1.385843
 x' mom.  Cl'|    Cla =   0.000000    Clb =  -0.528024
 y  mom.  Cm |    Cma =  -1.422702    Cmb =  -0.000000
 z' mom.  Cn'|    Cna =   0.000000    Cnb =   0.043876

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.000000    CLq =  -2.442555    CLr =   0.000000
 y  force CY |    CYp =  -0.855707    CYq =  -0.000000    CYr =   0.030203
 x' mom.  Cl'|    Clp =  -0.340108    Clq =  -0.000000    Clr =   0.012741
 y  mom.  Cm |    Cmp =  -0.000000    Cmq =  -0.516606    Cmr =   0.000000
 z' mom.  Cn'|    Cnp =   0.028242    Cnq =  -0.000000    Cnr =  -0.008172

                  Simetrico    d1     Asimetrico   d2 
                  ----------------    ----------------
 z' force CL |   CLd1 =   0.021805   CLd2 =   0.000000
 y  force CY |   CYd1 =   0.000000   CYd2 =   0.013696
 x' mom.  Cl'|   Cld1 =   0.000000   Cld2 =   0.004665
 y  mom.  Cm |   Cmd1 =   0.000491   Cmd2 =   0.000000
 z' mom.  Cn'|   Cnd1 =   0.000000   Cnd2 =   0.000320
 Trefftz drag| CDffd1 =   0.001006 CDffd2 =   0.000000
 span eff.   |    ed1 =  -0.002454    ed2 =  -0.000000



 Neutral point  Xnp =   1.008884

 Clb Cnr / Clr Cnb  =   7.718110    (  > 1 if spirally stable )
